### PR TITLE
Defer to bluesky.utils MsgGenerator

### PR DESCRIPTION
**Pull request by DiamondJoseph**
Companion change to https://github.com/DiamondLightSource/dodal/pull/832

### CODE REVIEW

**Review by DominicOram — CHANGES_REQUESTED** [review]
I think the test failure is real and implies that `blueAPI` is not picking up plans annotated with the `MsgGenerator` from `bluesky`. Do we need to update `blueAPI` as part of this?

**Comment by DominicOram** [comment]
@DiamondJoseph, what is the state of this? I think it may be the more long term fix for https://github.com/DiamondLightSource/mx-bluesky/pull/656. Would you like one of MX to pick it up?

**Comment by DiamondJoseph** [comment]
@DominicOram now that blueapi 0.6.1 has been released with support for bluesky>=1.13 this should be good to go after merge errors resolved. I'll quickly knock those on the head now.

**Review by DominicOram — APPROVED** [review]
Great, thank you!

**Pull request merged**
